[package]
name = "tokio-ar"
version = "0.9.0"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>", "kpcyrd <git@rxv.cc>"]
description = "A library for encoding/decoding Unix archive files."
repository = "https://github.com/mdsteele/rust-ar"
keywords = ["ar", "archive", "deb"]
license = "MIT"
readme = "README.md"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["io-util", "fs"] }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["io-util", "macros", "rt-multi-thread", "fs"] }
